/*
 * Licensed to the Hipparchus project under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The Hipparchus project licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.hipparchus.analysis.integration.gauss;

import org.hipparchus.special.Erf;
import org.hipparchus.util.Binary64;
import org.hipparchus.util.Binary64Field;
import org.hipparchus.util.FastMath;
import org.hipparchus.util.Pair;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

/**
 * Tests field-based Gauss-Chebyshev quadrature rules of the second kind against
 * reference data generated by the {@code GenGCQuad} MATLAB function from NASA's
 * CARA Analysis Tools.
 *
 * @see <a href="https://github.com/nasa/CARA_Analysis_Tools">NASA CARA Analysis Tools</a>
 */
class FieldChebyshevSecondKindTest {

    private static final double TOLERANCE = 1.0e-15;

    @Test
    void matchesGenGCQuadSixteenPointTableAfterPcCircleWeightConversion() {
        assertMatchesGenGCQuadTable(ChebyshevSecondKindTest.GEN_GC_QUAD_16);
    }

    @Test
    void matchesGenGCQuadSixtyFourPointTableAfterPcCircleWeightConversion() {
        assertMatchesGenGCQuadTable(ChebyshevSecondKindTest.GEN_GC_QUAD_64);
    }

    /**
     * Verifies that the generated quadrature rule matches one of the reference
     * tables in the {@code GenGCQuad} MATLAB function after converting the
     * standard second-kind weights to the table's PcCircle weight convention.
     *
     * @param genGcQuadTable reference table from {@code GenGCQuad}
     */
    private static void assertMatchesGenGCQuadTable(final double[][] genGcQuadTable) {
        final int order = genGcQuadTable.length;

        final FieldChebyshevSecondKindRuleFactory<Binary64> factory =
                new FieldChebyshevSecondKindRuleFactory<>(Binary64Field.getInstance());
        final Pair<Binary64[], Binary64[]> rule = factory.getRule(order);

        final Binary64[] secondKindPoints = rule.getFirst();
        final Binary64[] secondKindWeights = rule.getSecond();

        Assertions.assertEquals(order, secondKindPoints.length);
        Assertions.assertEquals(order, secondKindWeights.length);

        for (int tableIndex = 0; tableIndex < order; tableIndex++) {
            final double expectedX = genGcQuadTable[tableIndex][0];
            final double expectedY = genGcQuadTable[tableIndex][1];
            final double expectedPcCircleWeight = genGcQuadTable[tableIndex][2];

            final Binary64 x = secondKindPoints[tableIndex];
            final Binary64 y = FastMath.sqrt(Binary64.ONE.subtract(x.square()));

            /*
             * Standard second-kind weight:
             *
             *   W = pi / (n + 1) * sin^2(theta)
             *
             * PcCircle-customized table weight:
             *
             *   wGC = pi / (n + 1) * sin(theta) / sqrt(8*pi)
             *
             * Since y = sin(theta):
             *
             *   wGC = W / y / sqrt(8*pi)
             */
            final Binary64 pcCircleWeight =
                    secondKindWeights[tableIndex].divide(y).divide(FastMath.sqrt(8.0 * FastMath.PI));

            Assertions.assertEquals(expectedX, x.getReal(), TOLERANCE, "xGC mismatch at table index " + tableIndex);
            Assertions.assertEquals(expectedY, y.getReal(), TOLERANCE, "yGC mismatch at table index " + tableIndex);
            Assertions.assertEquals(expectedPcCircleWeight, pcCircleWeight.getReal(), TOLERANCE,
                                    "wGC mismatch at table index " + tableIndex);
        }
    }

    @Test
    void matchesMatlabPcCircleIntegrandForModerateOffsetWithOrder16() {
        assertMatchesMatlabReference(
                0.35,
                0.20,
                1.10,
                0.75,
                0.45,
                16,
                1.06055364621781625e-01
        );
    }

    @Test
    void matchesMatlabPcCircleIntegrandForModerateOffsetWithOrder64() {
        assertMatchesMatlabReference(
                0.35,
                0.20,
                1.10,
                0.75,
                0.45,
                64,
                1.06055364621781625e-01
        );
    }

    @Test
    void matchesMatlabPcCircleIntegrandForNearCenterWithOrder16() {
        assertMatchesMatlabReference(
                0.05,
                0.08,
                0.80,
                1.25,
                0.30,
                16,
                4.37336618192281021e-02
        );
    }

    @Test
    void matchesMatlabPcCircleIntegrandForNearCenterWithOrder64() {
        assertMatchesMatlabReference(
                0.05,
                0.08,
                0.80,
                1.25,
                0.30,
                64,
                4.37336618192281021e-02
        );
    }

    @Test
    void matchesMatlabPcCircleIntegrandForLargerRadiusWithOrder16() {
        assertMatchesMatlabReference(
                0.90,
                0.40,
                1.50,
                0.65,
                0.70,
                16,
                1.56273946267817959e-01
        );
    }

    @Test
    void matchesMatlabPcCircleIntegrandForLargerRadiusWithOrder64() {
        assertMatchesMatlabReference(
                0.90,
                0.40,
                1.50,
                0.65,
                0.70,
                64,
                1.56273946267818015e-01
        );
    }

    private static void assertMatchesMatlabReference(final double xm,
                                                     final double zm,
                                                     final double sx,
                                                     final double sz,
                                                     final double hbr,
                                                     final int order,
                                                     final double expected) {
        final Binary64 actual = integratePcCircleStyle(
                new Binary64(xm),
                new Binary64(zm),
                new Binary64(sx),
                new Binary64(sz),
                new Binary64(hbr),
                order
        );

        Assertions.assertEquals(expected, actual.getReal(), TOLERANCE,
                                "PcCircle-style field second-kind quadrature mismatch for order " + order);
    }

    /**
     * Uses the quadrature rule in the PcCircle convention to test probability of
     * collision calculations against MATLAB results for simple reference cases.
     *
     * @param xm    projected miss distance along the x-axis
     * @param zm    projected miss distance along the z-axis
     * @param sx    standard deviation along the x-axis
     * @param sz    standard deviation along the z-axis
     * @param hbr   hard-body radius
     * @param order quadrature rule order
     * @return probability of collision estimate
     */
    private static Binary64 integratePcCircleStyle(final Binary64 xm,
                                                   final Binary64 zm,
                                                   final Binary64 sx,
                                                   final Binary64 sz,
                                                   final Binary64 hbr,
                                                   final int order) {
        final FieldGaussIntegratorFactory<Binary64> factory =
                new FieldGaussIntegratorFactory<>(Binary64Field.getInstance());
        final FieldGaussIntegrator<Binary64> integrator = factory.chebyshevSecondKind(order);

        final Binary64 sqrt2 = FastMath.sqrt(new Binary64(2.0));
        final Binary64 dx = sx.multiply(sqrt2);
        final Binary64 dz = sz.multiply(sqrt2);

        final Binary64 integral = integrator.integrate(u -> {
            final Binary64 y = FastMath.sqrt(Binary64.ONE.subtract(u.square()));
            final Binary64 x = xm.add(hbr.multiply(u));
            final Binary64 hx = hbr.multiply(y);

            final Binary64 exponential = FastMath.exp(x.divide(dx).square().negate());
            final Binary64 errorFunctionDifference = Erf.erf(zm.subtract(hx).divide(dz),
                                                             zm.add(hx).divide(dz));

            /*
             * PcCircle's GenGCQuad convention uses:
             *
             *   wGC = pi / (n + 1) * y / sqrt(8*pi)
             *
             * while the standard second-kind rule uses:
             *
             *   W = pi / (n + 1) * y^2
             *
             * Therefore the integrand passed to FieldGaussIntegrator must include:
             *
             *   1 / (y * sqrt(8*pi))
             *
             * so that:
             *
             *   W * F(u) / (y * sqrt(8*pi)) == wGC * F(u)
             */
            return exponential.multiply(errorFunctionDifference)
                              .divide(y.multiply(FastMath.sqrt(8.0 * FastMath.PI)));
        });

        return hbr.divide(sx).multiply(integral);
    }
}